require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'vegastong' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # ios Vector아이콘 폰트 수동 경로 입력코드
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  # pod 'RNKakaoTest', :path => '../node_modules/react-native-kakao-test'

  target 'vegastongTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

#target 'vegastong-tvOS' do
#  # Pods for vegastong-tvOS
#
#  target 'vegastong-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#end
